### ISSUE TITLE
can't use my own web server

### ISSUE THREAD

**Issue by sparta34** [two06/Inception#2]
hi man thanks for this great tool , can i use my own web server for the payload ! like apache for exemple ! or just host the payload on pastbin and fetch it from there

**Comment by Gray-0men** [comment]
I'm able to change it using nano just fine.

for my I just changed the port to be something else, like 9999

at that point I just forward port 9999 to the IP of the machine running the server.py inside my router and boom, any computer connected to the internet can connect to the server.py 

you can test it by opening up a browser on any computer (or phone) that's not on your local network and just type out your IP address:9999 and you'll see your server.py respond to a "GET" attempt of some sort

my example below has it set to port 6666 but using my phone's browser I was able to get 4 responses when I attempted to go to myip:6666

![image](https://user-images.githubusercontent.com/39830524/44630151-2981ef00-a927-11e8-8ab2-63639ee8f7e9.png)

**Comment by two06** [comment]
I’m confused, what’s the issue here?

**Comment by sparta34** [comment]
ok thanks
