### ISSUE TITLE
updateservice.exe flaged

### ISSUE THREAD

**Issue by sparta34** [two06/Inception#6]
updateservice.exe is flagged by nod32 and kaspersky i've tired a lot to obfuscate it but nothing changed  can you help me on this thanks

**Comment by mrpogden** [comment]
Try the usual AV evasion techniques, they should work fine on traditional signature based AV

**Comment by fsacer** [comment]
That signature though:
![inceptionbotnet](https://user-images.githubusercontent.com/2059352/44949920-b521e100-ae3b-11e8-97a6-e2b0d4dfe054.PNG)
