### ISSUE TITLE
Updateservice compiling issue

### ISSUE THREAD

**Issue by stock99** [two06/Inception#7]
HI,
I am trying to compile the Roslyn code . It does compile without error but no http request initiated upon request.  Below is the screenshot of visual studio (version 15.9.3).  I have select the x64 as target platform but still can't get the updateservice.exe to work properly.  

![vs](https://user-images.githubusercontent.com/4704201/50480336-2a3b9800-0990-11e9-979a-c440748a45f9.jpg)

**Comment by two06** [comment]
are you running the exe in a VM? The sandbox detection stuff will stop it
running if you are. The easiest way to get around that is just to commend
out those checks.

**Comment by stock99** [comment]
Hi,
I removed the "if" clause (line 17~20) from program.cs and recompiled with x64(right click Project solution-> configuration manager-> select x64 for both active solution platform and platform under project contexts) .  I can see that updateservice.exe is sending something to my kali via nc listener(just for debugging purpose).  Note that i either run 443 with nc or msfconsole , not concurrently. 
![image](https://user-images.githubusercontent.com/4704201/50749246-c8353980-1291-11e9-8028-cf1a61eb07fa.png)
![image](https://user-images.githubusercontent.com/4704201/50748741-f107ff80-128e-11e9-8de3-a2718f9fc298.png)

edit1:  
Just run the file (without commenting out check) on physical windows machine.  I get about the same result.  Except that it pop up an error about 'RoslynLoad' has stopped working.  I wonder if version of vision stdio matter? Mine is 15.9.3 (community edition).

**Comment by kernel-sanders** [comment]
@stock99 Ensure you are feeding the RoslynLoad exe a `http` url not a `https` url. The content will be encrypted but the connection is not over TLS. From your `nc` screenshot it appears RoslynLoad is trying to establish an `https` connection to your kali box. The server used with inception only accepts `http` connections.
